version: '3.8'

services:
  # PostgreSQL Database
  james-db:
    image: postgres:15
    container_name: james-db
    environment:
      - POSTGRES_DB=james
      - POSTGRES_USER=james
      - POSTGRES_PASSWORD=james123
    volumes:
      - james_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Different port to avoid conflict with local PostgreSQL
    networks:
      - james-net

  # Apache James Mail Server
  james-server:
    image: apache/james:jpa-3.8.2
    container_name: james-server
    ports:
      - "143:143"     # IMAP
      - "993:993"     # IMAPS
      - "587:587"     # SMTP
      - "465:465"     # SMTPS
      - "8000:8000"   # WebAdmin
    environment:
      # Database connection (matches service name)
      - JAMES_DATABASE_URL=jdbc:postgresql://james-db:5432/james
      - JAMES_DATABASE_USERNAME=james
      - JAMES_DATABASE_PASSWORD=james123
    depends_on:
      - james-db
    networks:
      - james-net
    # Wait for database to be ready
    restart: unless-stopped

volumes:
  james_data:
    driver: local

networks:
  james-net:
    driver: bridge