global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'memail-prod'
    environment: 'production'

# Alerting configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Scrape configurations
scrape_configs:
  # Memail Backend Application
  - job_name: 'memail-backend'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['backend:8585']
        labels:
          application: 'memail-backend'
          service: 'backend'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          application: 'prometheus'
          service: 'monitoring'

  # Redis Exporter (optional - requires redis_exporter)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']
  #       labels:
  #         application: 'redis'
  #         service: 'cache'

  # PostgreSQL Exporter (optional - requires postgres_exporter)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']
  #       labels:
  #         application: 'postgres'
  #         service: 'database'
