spring:
  application:
    name: memail-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/memail
    username: memail
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  mail:
    imap:
      host: localhost
      port: 143
      ssl: false
      starttls: true
    smtp:
      host: localhost
      port: 587
      ssl: false
      starttls: true

server:
  port: 8585
  servlet:
    context-path: /api

logging:
  level:
    com.memail: DEBUG
    org.springframework.security: DEBUG
    org.springframework.mail: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

memail:
  jwt:
    secret: ${JWT_SECRET:mySecretKeyForMemailApplicationThatShouldBeChangedInProduction}
    expiration: 604800000 # 7 days in milliseconds
  cors:
    allowed-origins: http://localhost:4545
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true